version: '3.9'
services:
  mysql1:
    image: mysql:5.7
    container_name: db1
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
  node1:
    build: .
    container_name: nodejs1
    ports:
      - "80:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      mysql1:
        condition: service_started
    stdin_open: true
    tty: true
volumes:
  db: 
    driver: local